import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

INPUT_DIR = os.path.join(BASE_DIR, "input", "TableCfgOutput")
OUTPUT_DIR = os.path.join(BASE_DIR, "output")

os.makedirs(OUTPUT_DIR, exist_ok=True)

TARGET_LEVELS = [1, 20, 40, 60, 80, 90]

LANGUAGE_FILES = {
    "en": "I18nTextTable_EN.json",
    "cn": "I18nTextTable_CN.json",
    "tc": "I18nTextTable_TC.json",
    "jp": "I18nTextTable_JP.json",
    "kr": "I18nTextTable_KR.json",
    "sp": "I18nTextTable_MX.json",
    "ru": "I18nTextTable_RU.json",
}

ATTRIBUTE_TYPE = {
    0: "Level",
    1: "HP",
    2: "Attack",
    3: "Defense",
    4: "Physical DMG Reduction",
    5: "Heat DMG Reduction",
    6: "Electric DMG Reduction",
    7: "Cryo DMG Reduction",
    9: "Critical Rate",
    10: "Critical DMG",
    17: "Basic Attack DMG Bonus",
    26: "Stagger Efficiency Bonus",
    28: "Ultimate DMG Bonus",
    29: "Treatment Bonus",
    30: "Treatment Received Bonus",
    32: "Battle Skill DMG Bonus",
    33: "Combo Skill DMG Bonus",
    35: "Heat Burst DMG Increase",
    36: "Electric Burst DMG Increase",
    37: "Cryo Burst DMG Increase",
    38: "Nature Burst DMG Increase",
    39: "Strength",
    40: "Agility",
    41: "Intellect",
    42: "Will",
    44: "Ultimate Gain Efficiency",
    47: "Combo Skill Cooldown Reduction",
    48: "Nature DMG Reduction",
    49: "Arts Reaction and Burst DMG",
    50: "Physical DMG Bonus",
    51: "Heat DMG Bonus",
    52: "Electric DMG Bonus",
    53: "Cryo DMG Bonus",
    54: "Nature DMG Bonus",
    56: "Combustion Boost",
    57: "Electrification Boost",
    58: "Solidification Boost",
    59: "Corrosion Boost",
    60: "Æther DMG Reduction",
    61: "DMG Bonus vs. Staggered",
    80: "Physical Resistance",
    81: "Nature Resistance",
    82: "Cryo Resistance",
    83: "Electric Resistance",
    84: "Heat Resistance",
    85: "Æther Resistance",
    87: "Arts Intensity",
}

ATTRIBUTE_TYPE_RAW = {
    0: "Level",
    1: "MaxHp",
    2: "Atk",
    3: "Def",
    4: "PhysicalDamageTakenScalar",
    5: "FireDamageTakenScalar",
    6: "PulseDamageTakenScalar",
    7: "CrystDamageTakenScalar",
    8: "Weight",
    9: "CriticalRate",
    10: "CriticalDamageIncrease",
    11: "Hatred",
    12: "NormalAttackRange",
    13: "MoveSpeedScalar",
    14: "TurnRateScalar",
    15: "AttackRate",
    16: "SkillCooldownScalar",
    17: "NormalAttackDamageIncrease",
    18: "HpRecoveryPerSec",
    19: "HpRecoveryPerSecByMaxHpRatio",
    20: "MaxPoise",
    21: "PoiseRecTime",
    22: "MaxUltimateSp",
    23: "DamageTakenScalarWithPoise",
    24: "PoiseDamageTakenScalar",
    25: "PoiseProtectTime",
    26: "PoiseDamageOutputScalar",
    27: "BreakingAttackDamageTakenScalar",
    28: "UltimateSkillDamageIncrease",
    29: "HealOutputIncrease",
    30: "HealTakenIncrease",
    31: "PoiseRecTimeScalar",
    32: "NormalSkillDamageIncrease",
    33: "ComboSkillDamageIncrease",
    34: "KnockDownTimeAddition",
    35: "FireBurstDamageIncrease",
    36: "PulseBurstDamageIncrease",
    37: "CrystBurstDamageIncrease",
    38: "NaturalBurstDamageIncrease",
    39: "Str",
    40: "Agi",
    41: "Wisd",
    42: "Will",
    43: "LifeSteal",
    44: "UltimateSpGainScalar",
    45: "AtbCostAddition",
    46: "SkillCooldownAddition",
    47: "ComboSkillCooldownScalar",
    48: "NaturalDamageTakenScalar",
    49: "IgniteDamageScalar",
    50: "PhysicalDamageIncrease",
    51: "FireDamageIncrease",
    52: "PulseDamageIncrease",
    53: "CrystDamageIncrease",
    54: "NaturalDamageIncrease",
    55: "EtherDamageIncrease",
    56: "FireAbnormalDamageIncrease",
    57: "PulseAbnormalDamageIncrease",
    58: "CrystAbnormalDamageIncrease",
    59: "NaturalAbnormalDamageIncrease",
    60: "EtherDamageTakenScalar",
    61: "DamageToBrokenUnitIncrease",
    62: "WeaknessDmgScalar",
    63: "ShelterDmgScalar",
    64: "PhysicalEnhancedDmgIncrease",
    65: "FireEnhancedDmgIncrease",
    66: "PulseEnhancedDmgIncrease",
    67: "CrystEnhancedDmgIncrease",
    68: "NaturalEnhancedDmgIncrease",
    69: "EtherEnhancedDmgIncrease",
    70: "PhysicalVulnerableDmgIncrease",
    71: "FireVulnerableDmgIncrease",
    72: "PulseVulnerableDmgIncrease",
    73: "CrystVulnerableDmgIncrease",
    74: "NaturalVulnerableDmgIncrease",
    75: "EtherVulnerableDmgIncrease",
    76: "AtkIncreaseFactorFromStr",
    77: "AtkIncreaseFactorFromAgi",
    78: "AtkIncreaseFactorFromWisd",
    79: "AtkIncreaseFactorFromWill",
    80: "PhysicalDmgResistScalar",
    81: "NaturalDmgResistScalar",
    82: "CrystDmgResistScalar",
    83: "PulseDmgResistScalar",
    84: "FireDmgResistScalar",
    85: "EtherDmgResistScalar",
    86: "SlowActionSpeedScalar",
    87: "PhysicalAndSpellInflictionEnhance",
    88: "ShieldOutputIncrease",
    89: "ShieldTakenIncrease",
    90: "Enum",
  }

ATTRIBUTE_TYPE_ALT = {
    1: "HP",
    2: "ATK",
    9: "CR",
    12: "AR",
    15: "AS",
    39: "STR",
    40: "AGL",
    41: "INT",
    42: "WIL",
}

WEAPON_TYPE = {
    1: "Sword",
    2: "Arts Unit",
    3: "Great Sword",
    4: "Gun",
    5: "Polearm",
    6: "Handcannon",
}

ELEMENT_TYPE = {
    "Physical": "Physical",
    "Fire": "Heat",
    "Pulse": "Electric",
    "Cryst": "Cryo",
    "Natural": "Nature",
    "Ether": "Aether",
}

SPACESHIP_ROOM_TYPE = {
    0: "Control Nexus",
    1: "Manufacturing Cabin",
    2: "Growth Chamber",
    3: "Reception Room",
    4: "Command Center",
    5: "Reception Room",
    999996: "Any",
}

SPACESHIP_ROOM_TYPE_ALT = {
    0: "CN",
    1: "MFG",
    2: "GC",
    3: "RR",
    4: "CC",
    5: "RR",
    999996: "Any",
}

ITEM_TYPE_NAME = {
    1: "T-Creds",
    2: "Oroberyl",
    4: "Employment Contract",
    5: "Weapons",
    6: "Gear",
    7: "Operator EXP",
    8: "Naturals and Batteries",
    9: "Facilities and Plots",
    10: "PAC and SubPAC",
    11: "Factory Connections",
    12: "Templates and Expansions",
    13: "Quest",
    14: "Headhunting Permit",
    19: "Essences",
    21: "Sanity",
    22: "Sanity Recovery Items",
    25: "Weapon EXP",
    26: "Weapon Tuning Material",
    27: "Operator Progression Items",
    28: "Mining Spot",
    29: "Origeometry",
    32: "Dev TEST Items",
    33: "Gift",
    34: "Seed",
    37: "Operational EXP",
    38: "Daily Activity",
    39: "Crafting Formula",
    40: "Processing Upgrade",
    41: "Liquid Storage",
    42: "Potential Token",
    43: "Reward Containers",
    44: "Currency",
    45: "Decryption Crystal",
    47: "Gear Recipes",
    48: "Consumables Healing Items",
    49: "Supply Exchange Cert",
    50: "Stamina Delimiter",
    51: "Outpost Prosperity",
    52: "Meals and Explosives",
    53: "Region Bills Currency",
    54: "Deployable",
    55: "Item Finder",
    56: "Packages",
    58: "Photo Filter",
    59: "item_music_test_1",
    60: "Essence Kits",
    61: "Coolant Gel",
    63: "Sanity Recovery Items 2",
    64: "Recipe Blueprints",
    65: "Development Metric",
    66: "Portrait",
    67: "Frame",
    68: "Theme",
    69: "Trophy",
    70: "Photo Stickers",
    71: "Aurylene Crystal Nodules",
    72: "Aberrant Item",
    73: "Aberrant Item",
    74: "Aurylene Crystal",
    75: "Chips",
    76: "Snapshot",
    77: "Operation Metric",
    78: "Engraving Permit",
    79: "Arsenal Ticket",
    80: "Combat Facilities Capacity",
    82: "Headhunting Permit",
    83: "Headhunting Dossier",
    84: "Protocol Pass Experience",
    85: "Protocol Pass Tier",
    87: "Weapon Potential Upgrade",
    88: "Wuling Artificing Catalyst",
    89: "Monthly Pass",
    91: "Wuling Area Buff",
    92: "AIC Index",
    95: "High Tier Upgrade Item",
    96: "Mark of Perseverance",
    97: "Sanity Extractor",
    98: "Sanity Usage Permit"
}

DIALOGUE_TYPE = {
    "Operation Prep 1": 1,
    "Operation Prep 2": 2,
    "Added to Team 1": 3,
    "Added to Team 2": 4,
    "Switching Weapon": 5,
    "Switching Gear": 6,
    "Ability Matrix Activation": 7,
    "Watching Combat Records": 8,
    "Operator Promotion 1": 9,
    "Operator Promotion 2": 10,
    "Operator Promotion 3": 11,
    "Operator Promotion 4": 12,
    "Operator Reporting for Duty": 13,
    "Standing by 1": 14,
    "Standing by 2": 15,
    "Assigning to Facility": 16,
    "Greeting 1": 17,
    "Greeting 2": 18,
    "Dijiang Idle Chatter 1": 19,
    "Dijiang Idle Chatter 2": 20,
    "Dijiang Idle Chatter 3": 21,
    "Dijiang Idle Chatter 4": 22,
    "Dijiang Idle Chatter 5": 23,
    "Dijiang Idle Chatter 6": 24,
    "Offering Gifts": 25,
    "Accepting Gifts": 26,
    "Trust Dialog 1": 27,
    "Trust Dialog 2": 28,
    "Trust Dialog 3": 29,
    "Trust Dialog 4": 30,
    "Trust Dialog 5": 31,
    "Chat 1": 32,
    "Chat 2": 33,
    "Chat 3": 34,
    "Chat 4": 35,
    "Chat 5": 36,
    "Resource/Collectible Detected 1": 38,
    "Resource/Collectible Detected 2": 39,
    "Unexplored Area Detected": 40,
    "Powerful Enemy Discovered": 41,
    "Mining 1": 42,
    "Mining 2": 43,
    "Opening a Crate": 44,
    "Acquiring Aurylene": 45,
    "Eliminating the Blight": 46,
    "Rest": 47,
    "Tactical Use 1": 48,
    "Tactical Use 2": 49,
    "Danger Warning": 50,
    "Injured": 51,
    "0 HP": 52,
    "Team Encouragement 1": 53,
    "Team Encouragement 2": 54,
    "Encouragement Response 1": 55,
    "Encouragement Response 2": 56,
    "Combat Begins 1": 57,
    "Combat Begins 2": 58,
    "Combat Victory 1": 59,
    "Combat Victory 2": 60,
    "Combat Victory 3": 61,
    "Combat Victory 4": 62,
    "Combat Defeat": 63,
    "Final Strike 1": 64,
    "Final Strike 2": 65,
    "Battle Skill 1": 66,
    "Battle Skill 2": 67,
    "Battle Skill 3": 68,
    "Combo Skill Ready 1": 69,
    "Combo Skill Ready 2": 70,
    "Combo Casting 1": 71,
    "Combo Casting 2": 72,
    "Finisher 1": 73,
    "Finisher 2": 74,
    "Ultimate 1": 75,
    "Ultimate 2": 76,
    "Ultimate 3": 77,
}