import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

INPUT_DIR = os.path.join(BASE_DIR, "input", "TableCfgOutput")
OUTPUT_DIR = os.path.join(BASE_DIR, "output")

os.makedirs(OUTPUT_DIR, exist_ok=True)

LANGUAGE_FILES = {
    "en": "I18nTextTable_EN.json",
    "cn": "I18nTextTable_CN.json",
    "tc": "I18nTextTable_TC.json",
    "jp": "I18nTextTable_JP.json",
    "kr": "I18nTextTable_KR.json",
    "sp": "I18nTextTable_MX.json",
    "ru": "I18nTextTable_RU.json",
}

ATTRIBUTE_TYPE = {
    0: "Level",
    1: "HP",
    2: "Attack",
    3: "Defense",
    4: "PhysicalDamageTakenScalar",
    5: "FireDamageTakenScalar",
    6: "PulseDamageTakenScalar",
    7: "CrystDamageTakenScalar",
    8: "Weight",
    9: "Critical Rate",
    10: "Critical Damage Increase",
    11: "Hatred",
    12: "Attack Range",
    13: "MoveSpeedScalar",
    14: "TurnRateScalar",
    15: "Attack Rate",
    16: "Skill Cooldown",
    17: "NormalAttackDamageIncrease",
    18: "HpRecoveryPerSec",
    19: "HpRecoveryPerSecByMaxHpRatio",
    20: "Stagger Health",
    21: "Stagger Recovery Time",
    22: "MaxUltimateSp",
    23: "DamageTakenScalarWithPoise",
    24: "PoiseDamageTakenScalar",
    25: "PoiseProtectTime",
    26: "PoiseDamageOutputScalar",
    27: "BreakingAttackDamageTakenScalar",
    28: "UltimateSkillDamageIncrease",
    29: "HealOutputIncrease",
    30: "HealTakenIncrease",
    31: "PoiseRecTimeScalar",
    32: "NormalSkillDamageIncrease",
    33: "ComboSkillDamageIncrease",
    34: "KnockDownTimeAddition",
    35: "FireBurstDamageIncrease",
    36: "PulseBurstDamageIncrease",
    37: "CrystBurstDamageIncrease",
    38: "NaturalBurstDamageIncrease",
    39: "Strength",
    40: "Agility",
    41: "Intellect",
    42: "Will",
    43: "Life Steal",
    44: "UltimateSpGainScalar",
    45: "AtbCostAddition",
    46: "SkillCooldownAddition",
    47: "ComboSkillCooldownScalar",
    48: "NaturalDamageTakenScalar",
    49: "IgniteDamageScalar",
    50: "PhysicalDamageIncrease",
    51: "FireDamageIncrease",
    52: "PulseDamageIncrease",
    53: "CrystDamageIncrease",
    54: "NaturalDamageIncrease",
    55: "EtherDamageIncrease",
    56: "FireAbnormalDamageIncrease",
    57: "PulseAbnormalDamageIncrease",
    58: "CrystAbnormalDamageIncrease",
    59: "NaturalAbnormalDamageIncrease",
    60: "EtherDamageTakenScalar",
    61: "DamageToBrokenUnitIncrease",
    62: "WeaknessDmgScalar",
    63: "ShelterDmgScalar",
    64: "PhysicalEnhancedDmgIncrease",
    65: "FireEnhancedDmgIncrease",
    66: "PulseEnhancedDmgIncrease",
    67: "CrystEnhancedDmgIncrease",
    68: "NaturalEnhancedDmgIncrease",
    69: "EtherEnhancedDmgIncrease",
    70: "PhysicalVulnerableDmgIncrease",
    71: "FireVulnerableDmgIncrease",
    72: "PulseVulnerableDmgIncrease",
    73: "CrystVulnerableDmgIncrease",
    74: "NaturalVulnerableDmgIncrease",
    75: "EtherVulnerableDmgIncrease",
    76: "AtkIncreaseFactorFromStr",
    77: "AtkIncreaseFactorFromAgi",
    78: "AtkIncreaseFactorFromWisd",
    79: "AtkIncreaseFactorFromWill",
    80: "Pysical Resistance",
    81: "Nature Resistance",
    82: "Cryo Resistance",
    83: "Electric Resistance",
    84: "Heat Resistance",
    85: "Aether Resistance",
    86: "SlowActionSpeedScalar",
    87: "PhysicalAndSpellInflictionEnhance",
    88: "ShieldOutputIncrease",
    89: "ShieldTakenIncrease",
    90: "Enum",
  }