import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

INPUT_DIR = os.path.join(BASE_DIR, "input", "TableCfgOutput")
OUTPUT_DIR = os.path.join(BASE_DIR, "output")

os.makedirs(OUTPUT_DIR, exist_ok=True)

TARGET_LEVELS = [1, 20, 40, 60, 80, 99]

LANGUAGE_FILES = {
    "en": "I18nTextTable_EN.json",
    "cn": "I18nTextTable_CN.json",
    "tc": "I18nTextTable_TC.json",
    "jp": "I18nTextTable_JP.json",
    "kr": "I18nTextTable_KR.json",
    "sp": "I18nTextTable_MX.json",
    "ru": "I18nTextTable_RU.json",
}

ATTRIBUTE_TYPE = {
    0: "Level",
    1: "HP",
    2: "Attack",
    3: "Defense",
    4: "Physical DMG Reduction",
    5: "Heat DMG Reduction",
    6: "Electric DMG Reduction",
    7: "Cryo DMG Reduction",
    9: "Critical Rate",
    10: "Critical DMG",
    17: "Basic Attack DMG Bonus",
    26: "Stagger Efficiency Bonus",
    28: "Ultimate DMG Bonus",
    29: "Treatment Bonus",
    30: "Treatment Received Bonus",
    32: "Battle Skill DMG Bonus",
    33: "Combo Skill DMG Bonus",
    35: "Heat Burst DMG Increase",
    36: "Electric Burst DMG Increase",
    37: "Cryo Burst DMG Increase",
    38: "Nature Burst DMG Increase",
    39: "Strength",
    40: "Agility",
    41: "Intellect",
    42: "Will",
    44: "Ultimate Gain Efficiency",
    47: "Combo Skill Cooldown Reduction",
    48: "Nature DMG Reduction",
    49: "Arts Reaction and Burst DMG",
    50: "Physical DMG Bonus",
    51: "Heat DMG Bonus",
    52: "Electric DMG Bonus",
    53: "Cryo DMG Bonus",
    54: "Nature DMG Bonus",
    56: "Combustion Boost",
    57: "Electrification Boost",
    58: "Solidification Boost",
    59: "Corrosion Boost",
    60: "Æther DMG Reduction",
    61: "DMG Bonus vs. Staggered",
    80: "Physical Resistance",
    81: "Nature Resistance",
    82: "Cryo Resistance",
    83: "Electric Resistance",
    84: "Heat Resistance",
    85: "Æther Resistance",
    87: "Arts Intensity",
}

ATTRIBUTE_TYPE_RAW = {
    0: "Level",
    1: "MaxHp",
    2: "Atk",
    3: "Def",
    4: "PhysicalDamageTakenScalar",
    5: "FireDamageTakenScalar",
    6: "PulseDamageTakenScalar",
    7: "CrystDamageTakenScalar",
    8: "Weight",
    9: "CriticalRate",
    10: "CriticalDamageIncrease",
    11: "Hatred",
    12: "NormalAttackRange",
    13: "MoveSpeedScalar",
    14: "TurnRateScalar",
    15: "AttackRate",
    16: "SkillCooldownScalar",
    17: "NormalAttackDamageIncrease",
    18: "HpRecoveryPerSec",
    19: "HpRecoveryPerSecByMaxHpRatio",
    20: "MaxPoise",
    21: "PoiseRecTime",
    22: "MaxUltimateSp",
    23: "DamageTakenScalarWithPoise",
    24: "PoiseDamageTakenScalar",
    25: "PoiseProtectTime",
    26: "PoiseDamageOutputScalar",
    27: "BreakingAttackDamageTakenScalar",
    28: "UltimateSkillDamageIncrease",
    29: "HealOutputIncrease",
    30: "HealTakenIncrease",
    31: "PoiseRecTimeScalar",
    32: "NormalSkillDamageIncrease",
    33: "ComboSkillDamageIncrease",
    34: "KnockDownTimeAddition",
    35: "FireBurstDamageIncrease",
    36: "PulseBurstDamageIncrease",
    37: "CrystBurstDamageIncrease",
    38: "NaturalBurstDamageIncrease",
    39: "Str",
    40: "Agi",
    41: "Wisd",
    42: "Will",
    43: "LifeSteal",
    44: "UltimateSpGainScalar",
    45: "AtbCostAddition",
    46: "SkillCooldownAddition",
    47: "ComboSkillCooldownScalar",
    48: "NaturalDamageTakenScalar",
    49: "IgniteDamageScalar",
    50: "PhysicalDamageIncrease",
    51: "FireDamageIncrease",
    52: "PulseDamageIncrease",
    53: "CrystDamageIncrease",
    54: "NaturalDamageIncrease",
    55: "EtherDamageIncrease",
    56: "FireAbnormalDamageIncrease",
    57: "PulseAbnormalDamageIncrease",
    58: "CrystAbnormalDamageIncrease",
    59: "NaturalAbnormalDamageIncrease",
    60: "EtherDamageTakenScalar",
    61: "DamageToBrokenUnitIncrease",
    62: "WeaknessDmgScalar",
    63: "ShelterDmgScalar",
    64: "PhysicalEnhancedDmgIncrease",
    65: "FireEnhancedDmgIncrease",
    66: "PulseEnhancedDmgIncrease",
    67: "CrystEnhancedDmgIncrease",
    68: "NaturalEnhancedDmgIncrease",
    69: "EtherEnhancedDmgIncrease",
    70: "PhysicalVulnerableDmgIncrease",
    71: "FireVulnerableDmgIncrease",
    72: "PulseVulnerableDmgIncrease",
    73: "CrystVulnerableDmgIncrease",
    74: "NaturalVulnerableDmgIncrease",
    75: "EtherVulnerableDmgIncrease",
    76: "AtkIncreaseFactorFromStr",
    77: "AtkIncreaseFactorFromAgi",
    78: "AtkIncreaseFactorFromWisd",
    79: "AtkIncreaseFactorFromWill",
    80: "PhysicalDmgResistScalar",
    81: "NaturalDmgResistScalar",
    82: "CrystDmgResistScalar",
    83: "PulseDmgResistScalar",
    84: "FireDmgResistScalar",
    85: "EtherDmgResistScalar",
    86: "SlowActionSpeedScalar",
    87: "PhysicalAndSpellInflictionEnhance",
    88: "ShieldOutputIncrease",
    89: "ShieldTakenIncrease",
    90: "Enum",
  }

ATTRIBUTE_TYPE_ALT = {
    1: "HP",
    2: "ATK",
    9: "CR",
    12: "AR",
    15: "AS",
    39: "STR",
    40: "AGL",
    41: "INT",
    42: "WIL",
}

WEAPON_TYPE = {
    1: "Sword",
    2: "Arts Unit",
    3: "Great Sword",
    4: "Gun",
    5: "Polearm",
    6: "Handcannon",
}

ELEMENT_TYPE = {
    "Physical": "Physical",
    "Fire": "Heat",
    "Pulse": "Electric",
    "Cryst": "Cryo",
    "Natural": "Nature",
    "Ether": "Aether",
}